const data = {
	products: [
		{
			name: "Free Shirt",
			slug: "free-shirt",
			category: "Shirts",
			image: "/images/shirt1.jpg",
			price: 70,
			brand: "GIPOSKI",
			rating: 4.5,
			numReviews: 8,
			countInStock: 20,
			description: "A popular shirt",
			isFeatured: true,
			banner: "/images/banner1.jpg",
		},
		{
			name: "Fit Shirt",
			slug: "fit-shirt",
			category: "Shirts",
			image: "/images/shirt2.jpg",
			price: 80,
			brand: "GIPOSKI",
			rating: 4.7,
			numReviews: 18,
			countInStock: 30,
			description: "A very popular shirt",
			isFeatured: true,
			banner: "/images/banner2.jpg",
		},
		{
			name: "Slim Shirt",
			slug: "slim-shirt",
			category: "Shirts",
			image: "/images/shirt3.jpg",
			price: 90,
			brand: "GIPOSKI",
			rating: 4.2,
			numReviews: 3,
			countInStock: 10,
			description: "A popular shirt",
			// isFeatured: true,
			// banner: '/images/banner3.jpg',
		},
		{
			name: "Golf Pants",
			slug: "golf-pants",
			category: "Pants",
			image: "/images/pants1.jpg",
			price: 90,
			brand: "GIPOSKI",
			rating: 3.5,
			numReviews: 80,
			countInStock: 2,
			description: "Smart looking pants",
			// isFeatured: true,
			// banner: '/images/banner4.jpg',
		},
		{
			name: "Fit Pants",
			slug: "fit-pants",
			category: "Pants",
			image: "/images/pants2.jpg",
			price: 95,
			brand: "GIPOSKI",
			rating: 4.0,
			numReviews: 7,
			countInStock: 25,
			description: "Smart looking pants",
			// isFeatured: true,
			// banner: '/images/banner4.jpg',
		},
		{
			name: "Classic Pants",
			slug: "classic-pants",
			category: "Shirts",
			image: "/images/pants3.jpg",
			price: 50,
			brand: "GIPOSKI",
			rating: 4.5,
			numReviews: 8,
			countInStock: 20,
			description: "A popular shirt",
			// isFeatured: true,
			// banner: '/images/banner1.jpg',
		},
	],
};

export default data;
